services:
  audiobookshelf:
    # 2025-05-13 update from 2.20.0 to 2.21.0
    # 2025-03-22 update from 2.17.7 to 2.20.0
    # 2025-01-13 update from 2.16.2 to 2.17.7
    # 2024-11-02 update from 2.13.4 to 2.16.2
    # 2024-09-23 update from 2.13.3 to 2.13.4
    # 2024-09-07 update from 2.12.3 to 2.13.3
    # 2024-08-10 update from 2.12.1 to 2.12.3
    # 2024-08-06 update from 2.11.0 to 2.12.1
    # 2024-07-07 update from 2.9.0 to 2.11.0
    # 2024-05-06 update from 2.8.1 to 2.9.0
    # 2024-04-03 update from 2.6.0 to 2.8.1
    # 2023-12-27 update from 2.6.0 to 2.7.0
    # 2023-12-01 update from 2.5.0 to 2.6.0
    # 2023-11-16 update from 2.4.4 to 2.5.0 (Epub ereader search)
    # 2023-10-19 update from 2.4.3 to 2.4.4 (epu on mobile fix)
    # 2023-09-21 update from 2.3.3 to 2.4.3
    image: ghcr.io/advplyr/audiobookshelf:2.21.0
    ports:
      - 13378:80
    volumes:
      - ${AUDIOBOOKS_VOLUME:-/Volumes/Space/Reading/audiobooks}:/audiobooks:${AUDIOBOOKS_ACCESS_MODE:-ro}
      - ./data/metadata:/metadata
      - ./data/config:/config
    restart: unless-stopped
