# Install just on Ubuntu:
# curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin/
# List available commands
default:
    just -l

# Status (docker compose)
status:
    docker compose ps


# The start target is a single line continued command, so that ENV_VARS can be set

# Start in production mode - or choose dev/prod when on galois
start:
    @ENV_VARS=""; \
    if [ "$(hostname -s)" = "galois" ]; then \
        echo "Running on galois, you probably want dev"; \
        TYPE=$(gum choose "dev" "prod"); \
        if [ "$TYPE" = "dev" ]; then \
            ENV_VARS="AUDIOBOOKS_VOLUME=./data/audiobooks AUDIOBOOKS_ACCESS_MODE=rw"; \
        fi \
    fi; \
    echo $ENV_VARS docker compose up -d \
    $ENV_VARS docker compose up -d

# Stop the application
stop:
    docker compose down

# Exec into the container
exec:
    docker compose exec audiobookshelf ash
# Show logs
logs:
    docker compose logs -f    