# Install just on Ubuntu:
# curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin/
# List available commands
default:
    just -l

# Status (docker compose)
status:
    docker-compose ps
    
# Start in development mode
dev:
    AUDIOBOOKS_VOLUME=./data/audiobooks AUDIOBOOKS_ACCESS_MODE=rw docker-compose up -d
# Start in production mode
start:
    docker-compose up -d

# Stop the application
stop:
    docker-compose down

# Exec into the container
exec:
    docker-compose exec audiobookshelf ash
# Show logs
logs:
    docker-compose logs -f    