version: '3'

services:
  bragi:
    image: ghcr.io/djdembeck/bragibooks:main
    platform: linux/amd64 # <-- This is the line you add
    container_name: bragibooks
    environment:
      - CSRF_TRUSTED_ORIGINS=https://bragibooks.mydomain.com
      - LOG_LEVEL=INFO
      - DEBUG=False
      - UID=1000
      - GID=1000
    volumes:
      # - ./data/audiobooks:/audiobooks
      - ./data/config:/config
      - ./data/input:/input
      - ./data/output/output:/output
      - ./data/done:/done
    ports:
      - 8000:8000
    restart: unless-stopped
