name: CI - all packages

on:
  push:
    # branches: [main] # default is all branches
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7 # required

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Report versions
        run: |
          echo "node: $(node --version)"
          echo "pnpm: $(pnpm --version)"
          echo $(ffmpeg -version|head -2)
          echo $(ffprobe -version|head -2)

      - name: install dependencies
        # --frozen-lockfile should already be default on CI
        run: pnpm install --frozen-lockfile --loglevel error

      - name: Build First # must build first because lint/test will not work
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build (Again 8-))
        run: pnpm build
